version: '3.8'

services:
  fantasy-football-draft-assistant:
    build: .
    container_name: fantasy-football-draft-assistant
    ports:
      - "3000:3000"  # Frontend
      - "5001:5001"  # Backend API
    volumes:
      - ./src/backend/rankings:/app/backend/rankings  # Persist rankings data
    environment:
      - NODE_ENV=production
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s