### SEE THE README FILE FOR THE CORRECT CHANGES TO MAKE HERE!
### THIS IS THE ONLY FILE YOU WILL NEED TO EDIT!

### THE ID OF YOUR LEAGUE (Get this from the URL of your league in your browser)
### REQUIRED CHANGE
DRAFT_ID = '1128860872387973120'

### THE NAME OF YOUR RANKINGS FILE ("Rankings.csv" is the default)
### OPTIONAL CHANGE
FILE_NAME = 'Rankings.csv'
